CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TYPE public.jobstatus AS ENUM (
    'queued',
    'processing',
    'done',
    'not_found',
    'error'
);

ALTER TYPE public.jobstatus OWNER TO dt_admin;

CREATE TABLE public.assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_name TEXT,
    sf_asset_id BIGINT UNIQUE,
    CONSTRAINT pk_assets PRIMARY KEY (asset_id)
);

ALTER TABLE public.assets OWNER TO dt_admin;

CREATE TABLE public.ranges (
    ranges_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    range_ok_upper REAL,
    range_ok_lower REAL,
    range_warn_upper REAL,
    range_warn_lower REAL,
    range_crit_upper REAL,
    range_crit_lower REAL,
    CONSTRAINT pk_ranges PRIMARY KEY (ranges_id)
);

ALTER TABLE public.ranges OWNER TO dt_admin;

CREATE TABLE public.measurement_types (
    measurement_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    measurement_type_name TEXT,
    unit TEXT NOT NULL,
    CONSTRAINT pk_measurement_types PRIMARY KEY (measurement_type_id)
);

ALTER TABLE public.measurement_types OWNER TO dt_admin;

CREATE TABLE public.failure_types (
    failure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    failure_type_name TEXT,
    is_preventive BOOLEAN,
    failure_cause_id BIGINT,
    CONSTRAINT pk_failure_types PRIMARY KEY (failure_type_id)
);

ALTER TABLE public.failure_types OWNER TO dt_admin;

CREATE TABLE public.sensor_types (
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type_name TEXT NOT NULL,
    max_value REAL,
    min_value REAL,
    measurement_type_id BIGINT NOT NULL,
    accuracy REAL,
    CONSTRAINT pk_sensor_types PRIMARY KEY (type_id),
    CONSTRAINT fk_sensor_types_measurement_types
        FOREIGN KEY (measurement_type_id)
        REFERENCES public.measurement_types (measurement_type_id)
);

ALTER TABLE public.sensor_types OWNER TO dt_admin;

CREATE TABLE public.asset_failure_types (
    asset_failure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id BIGINT NOT NULL,
    failure_type_id BIGINT,
    default_occurrence_probability REAL,
    severity INTEGER,
    asset_failurecause_id BIGINT,
    CONSTRAINT pk_asset_failure_types PRIMARY KEY (asset_failure_type_id),
    CONSTRAINT fk_asset_failure_types_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_asset_failure_types_failure_types
        FOREIGN KEY (failure_type_id)
        REFERENCES public.failure_types (failure_type_id)
);

ALTER TABLE public.asset_failure_types OWNER TO dt_admin;

CREATE TABLE public.sensors (
    sensor_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_name TEXT NOT NULL,
    measurement_frequency REAL,
    ranges_id BIGINT,
    type_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    metric_function_id BIGINT,
    CONSTRAINT pk_sensors PRIMARY KEY (sensor_id),
    CONSTRAINT fk_sensors_ranges
        FOREIGN KEY (ranges_id) REFERENCES public.ranges (ranges_id),
    CONSTRAINT fk_sensors_sensor_types
        FOREIGN KEY (type_id) REFERENCES public.sensor_types (type_id),
    CONSTRAINT fk_sensors_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id)
);

ALTER TABLE public.sensors OWNER TO dt_admin;

CREATE TABLE public.measurements (
    measurement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_id BIGINT NOT NULL,
    "time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    value REAL NOT NULL,
    CONSTRAINT pk_measurements PRIMARY KEY (measurement_id, "time"),
    CONSTRAINT fk_measurements_sensors
        FOREIGN KEY (sensor_id) REFERENCES public.sensors (sensor_id)
);

SELECT create_hypertable(
    'public.measurements',
    by_range('time'),
    if_not_exists => TRUE
);

ALTER TABLE public.measurements OWNER TO dt_admin;

CREATE TABLE public.etas_betas (
    eta_beta_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eta_value REAL NOT NULL,
    beta_value REAL NOT NULL,
    asset_failure_type_id BIGINT NOT NULL,
    learning_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_etas_betas PRIMARY KEY (eta_beta_id),
    CONSTRAINT fk_etas_betas_asset_failure_types
        FOREIGN KEY (asset_failure_type_id)
        REFERENCES public.asset_failure_types (asset_failure_type_id)
);

ALTER TABLE public.etas_betas OWNER TO dt_admin;

CREATE TABLE public.asset_worksheet_lists (
    asset_worksheet_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id BIGINT NOT NULL,
    maintenance_end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    source_sys_time TIMESTAMP WITHOUT TIME ZONE,
    asset_failure_type_id BIGINT,
    failure_start_time TIMESTAMP WITHOUT TIME ZONE,
    downtime_in_min BIGINT,
    sys_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_asset_worksheet_lists
        PRIMARY KEY (asset_worksheet_list_id, maintenance_end_date),
    CONSTRAINT fk_asset_worksheet_lists_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_asset_worksheet_lists_asset_failure_types
        FOREIGN KEY (asset_failure_type_id)
        REFERENCES public.asset_failure_types (asset_failure_type_id)
);

SELECT create_hypertable(
    'public.asset_worksheet_lists',
    by_range('maintenance_end_date'),
    if_not_exists => TRUE
);

ALTER TABLE public.asset_worksheet_lists OWNER TO dt_admin;

CREATE TABLE public.operations_done_lists (
    operations_done_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    operation_template_id BIGINT NOT NULL,
    asset_worksheet_list_id BIGINT NOT NULL,
    maintenance_end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_operations_done_lists PRIMARY KEY (operations_done_list_id),
    CONSTRAINT fk_operations_done_lists_asset_worksheet_lists
        FOREIGN KEY (asset_worksheet_list_id, maintenance_end_date)
        REFERENCES public.asset_worksheet_lists (
            asset_worksheet_list_id,
            maintenance_end_date
        )
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

ALTER TABLE public.operations_done_lists OWNER TO dt_admin;

CREATE TABLE public.prediction_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_hash CHARACTER VARYING(64) NOT NULL,
    payload JSON NOT NULL,
    status public.jobstatus NOT NULL,
    endpoint_type CHARACTER VARYING NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    workorder_id BIGINT NOT NULL,
    CONSTRAINT pk_prediction_jobs PRIMARY KEY (job_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_prediction_jobs_request_hash
    ON public.prediction_jobs (request_hash);

ALTER TABLE public.prediction_jobs OWNER TO dt_admin;

CREATE TABLE public.predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id BIGINT NOT NULL,
    asset_failure_type_id BIGINT,
    job_id BIGINT NOT NULL,
    CONSTRAINT pk_predictions PRIMARY KEY (prediction_id),
    CONSTRAINT fk_predictions_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_predictions_asset_failure_types
        FOREIGN KEY (asset_failure_type_id)
        REFERENCES public.asset_failure_types (asset_failure_type_id),
    CONSTRAINT fk_predictions_prediction_jobs
        FOREIGN KEY (job_id) REFERENCES public.prediction_jobs (job_id)
);

ALTER TABLE public.predictions OWNER TO dt_admin;

CREATE TABLE public.prediction_asset_levels (
    prediction_asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_id BIGINT NOT NULL,
    nowcast_reliability REAL NOT NULL,
    forecast_reliability REAL NOT NULL,
    nowcast_virtual_age REAL NOT NULL,
    forecast_virtual_age REAL NOT NULL,
    nowcast_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    forecast_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_prediction_asset_levels
        PRIMARY KEY (prediction_asset_id, forecast_time),
    CONSTRAINT fk_prediction_asset_levels_predictions
        FOREIGN KEY (prediction_id) REFERENCES public.predictions (prediction_id)
);

SELECT create_hypertable(
    'public.prediction_asset_levels',
    by_range('forecast_time'),
    if_not_exists => TRUE
);

ALTER TABLE public.prediction_asset_levels OWNER TO dt_admin;

CREATE TABLE public.prediction_asset_failure_type_levels (
    prediction_asset_failure_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_id BIGINT NOT NULL,
    nowcast_failure_type_probability REAL NOT NULL,
    forecast_failure_type_probability REAL NOT NULL,
    nowcast_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    forecast_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_prediction_asset_failure_type_levels
        PRIMARY KEY (prediction_asset_failure_id, forecast_time),
    CONSTRAINT fk_prediction_asset_failure_type_levels_predictions
        FOREIGN KEY (prediction_id) REFERENCES public.predictions (prediction_id)
);

SELECT create_hypertable(
    'public.prediction_asset_failure_type_levels',
    by_range('forecast_time'),
    if_not_exists => TRUE
);

ALTER TABLE public.prediction_asset_failure_type_levels OWNER TO dt_admin;

CREATE TABLE public.sensor_failure_types (
    sensor_failure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_id BIGINT NOT NULL,
    failure_type_id BIGINT NOT NULL,
    CONSTRAINT pk_sensor_failure_types PRIMARY KEY (sensor_failure_type_id),
    CONSTRAINT fk_sensor_failure_types_sensors
        FOREIGN KEY (sensor_id) REFERENCES public.sensors (sensor_id),
    CONSTRAINT fk_sensor_failure_types_failure_types
        FOREIGN KEY (failure_type_id) REFERENCES public.failure_types (failure_type_id)
);

ALTER TABLE public.sensor_failure_types OWNER TO dt_admin;

CREATE TABLE public.sensor_statistics (
    sensor_statistic_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_id BIGINT NOT NULL,
    standard_deviation_value REAL NOT NULL,
    average_value REAL NOT NULL,
    learning_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_sensor_statistics PRIMARY KEY (sensor_statistic_id),
    CONSTRAINT fk_sensor_statistics_sensors
        FOREIGN KEY (sensor_id) REFERENCES public.sensors (sensor_id)
);

ALTER TABLE public.sensor_statistics OWNER TO dt_admin;

CREATE TABLE public.gammas (
    gamma_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    gamma_value REAL NOT NULL,
    sensor_failure_type_id BIGINT NOT NULL,
    contribution REAL NOT NULL,
    learning_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_gammas PRIMARY KEY (gamma_id),
    CONSTRAINT fk_gammas_sensor_failure_types
        FOREIGN KEY (sensor_failure_type_id)
        REFERENCES public.sensor_failure_types (sensor_failure_type_id)
);

ALTER TABLE public.gammas OWNER TO dt_admin;
